### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by samdroid-apps**
I was going to fix the wayland area chooser; but then I got a little overboard on the re-factoring.  This might end up being a fork; but TL;DR:

* Moved most of your global state into a class that makes more sense
* Moved recorder backends into self-contained classes
* Setup a build system so we can have proper gresources files (relocateable even!)
* Port to python3
* Use Gtk.Application
* New clean preferences window design

There is probs more coming :smile:

### CODE REVIEW

**Comment by mhsabbagh** [comment]
Well I can't merge it from here due to the conflicts. It would be great if can take care of it.

Anyway, there are multiple issues regarding this pull request:

* While you do own the copyright on your contributions, only "FOSS Project" is mentioned as the copyright holder in the about page for all the software which are being developed. Your name will be listed there and in the files (which you already did and will stay there). But, there's only one "© FOSS Project, 2017" in all the programs which we'll develop. This has no legal consequences. As the way of mentioning the copyright holders doesn't affect who owns the copyright. 

* You'll also have to remove resources names like  <gresource prefix="/today/sam/green-recorder"> and replace them with things like /fossproject/green-recorder.

* All text assigning should be done from the Python files using gettext. No text (or translatable text) should be used in the UI files.

* From what I understood from the code you dropped support for Python 2. This is a something which I can't do by default. Both Python 2 & 3 should be supported if we are going to remove forward. As there are a lot of distributions and users who don't have/offer Python 3. And also since we don't have pydbus packaged for Python 3 yet in the PPA AFAIK.

* We also need keeping the setup.py (using distutils module) and the build method as it is because we need building it for Launchpad PPA and with openSUSE build service (which builds for Fedora and possibly other distros soon). I have no idea how to achieve this with Mason.

**Comment by samdroid-apps** [comment]
> While you do own the copyright on your contributions, only "FOSS Project" is mentioned as the copyright holder in the about page for all the software which are being developed. Your name will be listed there and in the files (which you already did and will stay there). But, there's only one "© FOSS Project, 2017" in all the programs which we'll develop. This has no legal consequences. As the way of mentioning the copyright holders doesn't affect who owns the copyright.

So I redesign your UI; make the code something actually readable and the first thing you tell me is that you don't like how I want to be in the about dialog?
 
> You'll also have to remove resources names like gresource prefix="/today/sam/green-recorder" and replace them with things like /fossproject/green-recorder.

I could, but it is convention that it is a reversed domain name; not a random identifier like "fossproject".

> All text assigning should be done from the Python files using gettext. No text (or translatable text) should be used in the UI files.

Thanks for actually commenting on the contents of the patch.

But I think your view is bizarre.  Putting text back in the glade files means:

* The glade files make more sense when editing them (no more "label" and "button1", etc.)
* You write less code (yay!)
* Use the translation code already written by the Gtk+ developers, better tested than just a single app

Other apps that use glade put the text in the `.ui` files; take GNOME Music (another python app) for example: https://wiki.gnome.org/Apps/Music

> 
> From what I understood from the code you dropped support for Python 2. This is a something which I can't do by default. Both Python 2 & 3 should be supported if we are going to remove forward. As there are a lot of distributions and users who don't have/offer Python 3. And also since we don't have pydbus packaged for Python 3 yet in the PPA AFAIK.

Pydbus works great on python3: (fedora)

    sudo dnf install python3-pydbus

I would assume debian has a similar package.

I'd also be amazed if you found and distros that didn't support python3.  [Python2 is 2 years away from being EOLed](https://pythonclock.org/).  I don't know why anybody would write a new Gtk+ app and do it in python2 only!

> We also need keeping the setup.py (using distutils module) and the build method as it is because we need building it for Launchpad PPA and with openSUSE build service (which builds for Fedora and possibly other distros soon). I have no idea how to achieve this with Mason.

Meson/ninja is slowly replacing autotools for gnome applications.  It lets you do ""big boy"" gnome application things; like using gresource files, etc.  It also means we are relocatable.

You literally need to just change the rpm spec file to run the appropriate meson commands.  Just find another app that uses meson (there are tones of GNOME libs that do, eg. https://github.com/vinszent/gnome-twitch) and copy the commands.  I'm not sure why you are so against proper build infrastructure.

Meson also means we get the nice `ninja green-recorder-pot` command, which rebuilds the POT file for translators.

TBH; I really don't care if you merge this.  If you want to continue to drag your feet; I'll just fork and get a nice icon and a nice name.  Professionalism is allowed in the FLOSS community; we don't have to all write 500loc python2 scripts with global variables everywhere.

**Comment by samdroid-apps** [comment]
Oh yeah, you probably haven't even looked; but here is what the new UI looks like currently.  New:

screenshot from 2017-08-13 11-33-37

Fully expanded (usually you can just scroll down):

screenshot from 2017-08-13 11-33-54

For comparison:

**Comment by mhsabbagh** [comment]
> So I redesign your UI; make the code something actually readable and the first thing you tell me is that you don't like how I want to be in the about dialog?

> I could, but it is convention that it is a reversed domain name; not a random identifier like "fossproject".

Yes. Because it's not very genuine to contribute to a piece of software, and then put your own name like: "Built by Mozilla and me" or "by GNOME and me". You should put your name in the authors list "Built by: User 1 <email>, User 2 <email>" just like any other software.

I don't even understand how the hell you submit a pull request to another software, and use a gresource name which has your personal name in it? Really?

> But I think your view is bizarre. Putting text back in the glade files means:

I believe putting it in Python is better since we'll have to run a single locale domain. It will also mean that we don't have to check two places to search for what's toggling this and that (We still have to set some text and print another from the Python files). Generating the pot file from the Python file where all the text is grouped is more organized.

> I would assume debian has a similar package.

I am talking about our PPA.

>  I don't know why anybody would write a new Gtk+ app and do it in python2 only!

Surprise! Python 2 is still even way more used than Python 3 and still default on a lot of distributions like Ubuntu, Fedora and Mint.

Good point about Mason. We may use it.

> TBH; I really don't care if you merge this. If you want to continue to drag your feet; I'll just fork and get a nice icon and a nice name. Professionalism is allowed in the FLOSS community; we don't have to all write 500loc python2 scripts with global variables everywhere.

Feel free to fork anything according to the license of GPL 3. Just remember in the future when you submit a pull request to use a proper gresource name which includes the project name, not your own personal name (for "Professionalism", eh).  

> Fully expanded (usually you can just scroll down):

That you mentioned it. I don't understand why the window is now taking full screen height.

**Comment by samdroid-apps** [comment]
You don't seem to be bringing a very positive or thought-out attitude towards creating an even better screen recording experience.  Sorry about that.On Aug 14, 2017 3:53 PM, "M.Hanny Sabbagh" <notifications@github.com> wrote:Closed #61.

**Comment by mhsabbagh** [comment]
Can you even believe yourself? You say "I don't even care if you merge this or not, I can create my fork alone". And you didn't answer to any modifications I requested. And you use your own personal name as a gresource name in pull request you are supposed to submit to another program. And you submit your new UI after my comment, and then tell me: "you probably didn't even check".. of course I didn't check if you just submitted it. And finally, you call me "so rude" on Reddit in an unrelated-thread I published, linking to this GitHub PR. Yet, you expect me to merge this for you? lol.

You have no idea how open source works at all. It's not just "hey, I made this nice thing, merge it in there". It doesn't work like that.

**Pull request closed without merging**
