### PR TITLE
Change the area selector so that it works on Wayland, fixes #30

### LINKED ISSUE #30: Cannot select area under Wayland
When running Gnome (3.22.2) on Wayland, and choosing "Select an Area" in Green Recorder (2.1.5), and then click "Apply" in the Area Chooser, nothing happens in the user interface, but following is logged to the terminal (I started `green-recorder` from):

```
/bin/sh: 1: aserver: not found
('No alsa found', 127)
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.
xwininfo: error: No window with name "Area Chooser" exists!
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 300, in areasettings
    output = subprocess.check_output(["xwininfo -name \"Area Chooser\" | grep -e Width -e Height -e Absolute"], shell=True)[:-1]
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['xwininfo -name "Area Chooser" | grep -e Width -e Height -e Absolute']' returned non-zero exit status 1
```

As far as I know, `xwininfo` isn't supposed to work for windows natively handled by Wayland, but only for windows managed by X (or XWayland). In fact, if I run `xwininfo` without options (or `xprop`), I cannot even click on any of Green Recorder's windows.

### PR DESCRIPTION
**Pull request by samdroid-apps**

### CODE REVIEW

**Comment by mhsabbagh** [comment]
I'll take a look at in in 10 days.

**Comment by mhsabbagh** [comment]
Thank you for submitting this! While I like the idea and concept very much. The method doesn't seem to be working with me here. After I choose the area I want and after I click in the middle of it (because there's nowhere else), nothing happens. It doesn't take the coordinates of the chosen area. Instead, it just records the whole screen.

You have some warnings as well about it:
```
green-recorder:391: SyntaxWarning: name 'WindowXAxis' is assigned to before global declaration
  global WindowXAxis, WindowYAxis, WindowWidth, WindowHeight
green-recorder:391: SyntaxWarning: name 'WindowYAxis' is assigned to before global declaration
  global WindowXAxis, WindowYAxis, WindowWidth, WindowHeight
green-recorder:391: SyntaxWarning: name 'WindowWidth' is assigned to before global declaration
  global WindowXAxis, WindowYAxis, WindowWidth, WindowHeight
green-recorder:391: SyntaxWarning: name 'WindowHeight' is assigned to before global declaration
  global WindowXAxis, WindowYAxis, WindowWidth, WindowHeight
```

Even when I managed somehow to get it to capture the coordinates, it couldn't record it properly:

`:0.0+703.360595703,0.0: Invalid argument`

So more testing and fixing is needed for this pull request :-)

**Comment by samdroid-apps** [comment]
Oh sorry @mhsabbagh that I fell behind on this one.  I can take another look and fix the issues if you want; or did this get fixed another way?

**Comment by mhsabbagh** [comment]
Well, the area selector still needs to be recreated. It needs _not_ to be a window just like we are using. But an area selector using the mouse cursor. If you can work on that, it would be great :-)

**Comment by samdroid-apps** [comment]
Awesome.  What do you mean by "using the mouse cursor"?  Do you mean like the area selector in GNOME Screenshots?On Aug 7, 2017 5:27 PM, "M.Hanny Sabbagh" <notifications@github.com> wrote:Well, the area selector still needs to be recreated. It needs not to be a window just like we are using. But an area selector using the mouse cursor. If you can work on that, it would be great :-)

**Comment by mhsabbagh** [comment]
Exactly. Even like the one you introduced in this pull request before. It depended on GtkDrawingArea.

**Pull request closed without merging**
